### ISSUE TITLE
ES* signatures are not spec compliant

### ISSUE THREAD

**Issue by omsmith** [jwtk/njwt#11]
Heyo - found myself here from another library.

Just had a quick look and it would appear _njwt_ also suffers the same problem as _jjwt_ from this organisation (https://github.com/jwtk/jjwt/issues/125). Just from looking at the library, it seems to me the "OpenSSL" ASN.1 encoded signature is being returned (and expected on verification) directly.

If it helps, I created [ecdsa-sig-formatter](https://github.com/Brightspace/node-ecdsa-sig-formatter) last year to solve the same problem with [node-jwa](https://github.com/brianloveswords/node-jwa) which you could easily add in.

**Comment by robertjd** [comment]
Thanks for the heads up!  We're going to look into this.
