### ISSUE TITLE
Potentially support kid header?

### ISSUE THREAD

**Issue by ethul** [jwtk/njwt#24]
I noticed in the README and in #14 that the `kid` is not currently supported. Just curious if there may be plans to add this? It is required by Apple's APNS provider authentication tokens. Note however, that unofficially adding the `kid` into the header seems to be working; e.g.,

```
jwt.header.kid = '<kid>';
```

**Comment by lhazlewood** [comment]
It is supported:

```
Jwts.builder().setHeader(Jwts.jwsHeader().setKeyId("whatever"))...
```

That said, if you'd prefer this to be easier, we're all ears - let us know any suggestions.

Cheers!

**Comment by robertjd** [comment]
Hi @ethul , thanks for the question.  Are you looking for an easier way to validate tokens when the signing key is indicated by the `kid` field in the header of the token?  That is definitely a lacking feature in this library, that is the key resolver that is mentioned in the README.  Just want to clarify, thanks!

**Comment by ethul** [comment]
Thanks for the prompt response.

Currently, I only need to set the `kid` in the JWT header. Doing as mentioned above does just that. I suppose I was wondering if there were plans to add a function like `setHeader(name, value)` , `setKID(value)`, or even adding the capability to provide headers in the call to `nJwt.create(...)`. Just curious!

**Comment by robertjd** [comment]
Thanks, adding a `setHeader()` method would be nice, I've opened an issue for us to do that, see #25.  I'm also opening up #26 so that we can get to work on that.  Thanks for the input!

**Comment by ethul** [comment]
Sounds good. Thanks again!
