### ISSUE TITLE
jti and iat overwritten during parse

### ISSUE THREAD

**Issue by WebWalks** [jwtk/njwt#4]
When verifying a token the jti and iat are both overwritten with newer values (new id for jti and new time for iat)
I want to track tokens issued via their jti.

I temp hacked your code to

**Comment by WebWalks** [comment]
fix the issue by modifying the constructor of Jwt

this.body = new JwtBody(claims);
  if (!this.body.jti) {
    this.setJti(uuid.v4());
  }
  if (!this.body.iat) {
    this.setIssuedAt(nowEpochSeconds());
  }

not sure if thats the best solution, but works for me!

**Comment by hilkeheremans** [comment]
Yup, also having this issue.
