### ISSUE TITLE
vulnerablity found - Out-of-bounds Read

### ISSUE THREAD

**Issue by Toxicable** [jwtk/njwt#62]
This package is currently maked as vulnerable see:
https://www.npmjs.com/advisories/679

**Comment by swiftone** [comment]
We patched that in the 1.0.0 version - I'll see if we can track down why the 1.0.0 version is also listed, but the report appears erroneous.  

I'll leave this issue open while I track that down, but please let me know if you know of any evidence that it's not corrected.

**Comment by swiftone** [comment]
They have now updated the advisory - thank you for your report!
