### ISSUE TITLE
Undocumented - Return in verify

### ISSUE THREAD

**Issue by fabltd** [jwtk/njwt#64]
When verify a JWT the following is returned header body and then:

toString: [Function]

What is the expected operation of toString. There is no mention in the docs.

**Comment by swiftone** [comment]
Hey @fabltd, thanks for the question: 

`toString()` is just an alias for `compact()` - it returns the JWT as a Base64 URL-encoded string rather than as a data object.  I recommend using `compact()`  for the sake of being explicit.

**Comment by fabltd** [comment]
Thanks. Suggest adding this to the docs.
