### ISSUE TITLE
Any plan to make the NJWT library support compression and decompression?

### ISSUE THREAD

**Issue by jjeanj1** [jwtk/njwt#65]
Are there any plans to have the njwt library supporting compression and decompression. The jjwt library supports both, this would be a great feature to add

**Comment by swiftone** [comment]
@jjeanj1 - Great question.  I'm not aware of any immediate plans, but I've sent your question around to see if I can get a more detailed answer.

**Comment by swiftone** [comment]
@jjean - There are no plans to add such features at this time, sorry to disappoint.  If/when we have a business call to add this, we'll revisit.  

Wish I had a more helpful answer, sorry.
