### ISSUE TITLE
body vs parsedBody

### ISSUE THREAD

**Issue by jmls** [jwtk/njwt#7]
After I verify a token, I want to look at the token payload. 

I have seen both body and parsedBody returned on the verified object - why are there two differences ?

```
 header: JwtHeader { typ: 'JWT', alg: 'HS256' },
  body: 
   JwtBody {

```
and
```
 parsedHeader: JwtHeader { typ: 'JWT', alg: 'HS256' },
  parsedBody: 
   JwtBody {
```

**Comment by jmls** [comment]
ah - it may be because I'm getting an error (token expired)

odd that the error has *parsedBody* but success has *body* though

**Comment by robertjd** [comment]
Thank you for the question.  For error cases, we chose a different property because we wanted to ensure that the error object was not the same structure as a verified token response.  We wanted to make it obvious that the token was un-verifiable.
