### ISSUE TITLE
error:0909006C:PEM routines:get_name:no start line

### ISSUE THREAD

**Issue by patil-akshay** [jwtk/njwt#70]
Getting the above error while trying to create an token using RS256.
`const signingKey = secureRandom(256, { type: 'Buffer' });
  const jwt = nJwt.create(claims, signingKey, 'RS256');`

**Comment by swiftone** [comment]
@patil-akshay - Thanks for the report.  I believe your issue will be addressed if you use the public key as your signing key.  See https://github.com/jwtk/njwt#changing-the-algorithm

> If using RSA key pairs, the public key will be the signing key parameter.

Hope that helps!

**Comment by swiftone** [comment]
Closing as this issue appears to be resolved.  Feel free to reopen with details if that is not the case.
